trying clean architecture for listing list page
CSC207-2022F-UofT/course-project-scamazon-ca-group-118 pull request #43
Opened 2022-11-12 05:02 UTC by liu-samuel

I also tried to follow what Clare did, but I don't think the response and request models are relavant for something that just displays listings. Same goes with the creator and interactor since there is not interaction with the user and the user isn't creating anything.

2022-11-12 17:29 UTC, danielqiuu reviewed
We might have merge conflicts because I too have a ListingDatabaseController and ListingDatabaseGateway, should I be renaming my ListingDatabaseController and ListingDatabaseGateway or should we implement both of them in one class. (I am doing create a listing)

2022-11-14 21:42 UTC, MarkianV requested changes
We need to decide how the search will be implemented.

2022-11-14 21:42 UTC, MarkianV commented on src/main/java/database/ListingDatabaseController.java
> +        // this will go through database and retrieve first 10 listings with keyword in the listing name
call (SearchForm instance).getResponseModel() and work with the response model that has a .getListings() method for a array list of listings that fit the query.

2022-11-14 21:48 UTC, danielqiuu approved these changes

2022-11-14 21:54 UTC, danielqiuu approved these changes

2022-11-14 21:54 UTC, helenastra approved these changes

2022-11-14 21:54 UTC, MarkianV approved these changes

2022-11-14 21:54 UTC, ericguo1230 approved these changes

2022-11-14 21:54 UTC, merged