Finished GUI for FORM
CSC207-2022F-UofT/course-project-scamazon-ca-group-118 pull request #48
Opened 2022-11-14 21:26 UTC by ericguo1230

GUI for Registration Form

2022-11-19 17:49 UTC, liu-samuel reviewed
Yeah like we said yesterday during our meeting we don't need to right hand side that sends a confirmation message

2022-11-20 04:08 UTC, liu-samuel requested changes
no need for implementation, we implement in the general controller

2022-11-20 23:24 UTC, lukecheseldine approved these changes

2022-11-20 23:25 UTC, liu-samuel approved these changes

2022-11-20 23:25 UTC, helenastra approved these changes

2022-11-20 23:25 UTC, claregillis approved these changes

2022-11-20 23:26 UTC, merged