Remove listing tests
CSC207-2022F-UofT/course-project-scamazon-ca-group-118 pull request #87
Opened 2022-12-05 07:04 UTC by liu-samuel

test for the method of remove listings. CHANGE THE DIRECTORY WHEN NOT DOING TESTS.

2022-12-05 08:04 UTC, lukecheseldine requested changes
you can't have people change the directory when not running tests. it needs to work without changing the hardcoded directory. when they run the project, they will run the tests with the same code. i know this is a pain, but you have to solve it.

also, you need to test that this method:
1. removes the listing from all users' carts in the database
2. removes the listing from the seller's listing array in the database

2022-12-05 23:24 UTC, danielqiuu approved these changes

2022-12-05 23:25 UTC, ericguo1230 submitted a review, later dismissed

2022-12-06 05:10 UTC, helenastra approved these changes

2022-12-06 23:17 UTC, lukecheseldine approved these changes

2022-12-06 23:25 UTC, claregillis approved these changes

2022-12-06 23:26 UTC, danielqiuu approved these changes

2022-12-06 23:27 UTC, merged